# Example file for Brans Dicke dark energy.
# See: Avilez+13 (1303.4330) or Bellini+17 (1709.09135) for details

# Brans-Dicke theory:
# - G_2 -> (omega_BD/phi)X -V0,
# - G_4 -> phi M_p^2/2
# Notes:
# - initial field value sets M_*^2 (effective Planck mass)

# Switch on _smg fluid
Omega_Lambda = 0.
Omega_fld = 0.
Omega_smg = -1.

# For debugging purpouses one can specify a Omega_smg_debug
# AND unspecify Omega_smg,fld,Lambda so no shooting is done
# Omega_smg_debug = -1.

# Gravity model and parameters
gravity_model = brans_dicke
# Names:            V0, omega_BD,  phi_ini,  phi_prime_ini
parameters_smg =   0.7,      15.,       1.,             1.

M2_tuning_smg = yes
# Options for tuning of effective M2 using phi_ini:
# a) no specifications uses the input_value
# b) specifying M2_today fixes phi_0 (overwrites phi_ini)
# c) specifying M2_today AND normalize_G_NR sets G_eff -> 1
#    for non-relativistic matter (overwrites phi_ini AND M2_today_smg)
# Note that (b,c) are very close for large omega_BD (viable models)
M2_today_smg = 1.
# normalize_G_NR = yes

# Sometimes it is necessary to change the initial conditions for the scalar
# field perturbations. Otherwise, the default one would flag a tachnionyc
# instability for some choices of parameters.
pert_initial_conditions_smg = zero

# Brans Dicke runs into some numerical problems at very early times
a_min_stability_test_smg = 1e-6

# Output:
output = tCl, mPk 

root = output/brans_dicke
overwrite_root = yes

output_background_smg = 10
write parameters = yeap
write background = yeah
write thermodynamics = yeahh

input_verbose = 1
background_verbose = 1
thermodynamics_verbose = 1
perturbations_verbose = 1
transfer_verbose = 1
primordial_verbose = 1
harmonic_verbose = 1
fourier_verbose = 1
lensing_verbose = 1
distortions_verbose = 1
output_verbose = 1
