# Example file for quintic covariant Galileon dark energy.
# See: Renk+17 (1707.02263) and Barreira+14 (1406.0485) for details

# Quintic Galileon theory:
# - G_2 -> -X,
# - G_3 -> c_3 X/(H_0^2M_p),
# - G_4 -> M_p^2/2 + c_4 X^2/(H_0^2M_p)^2
# - G_5 -> 3 c_5 X^2/(H_0^2M_p)^3
# Notes:
# - model specified by c_3, xi -> (H phi')/(a H0^2) ~ constant
# - other model parameters fixed by Omega_smg and the tracker condition

# Switch on _smg fluid
Omega_Lambda = 0.
Omega_fld = 0.
Omega_smg = -1.

# For debugging purpouses one can specify a Omega_smg_debug
# AND unspecify Omega_smg,fld,Lambda so no shooting is done
# Omega_smg_debug = -1.

# Gravity model and parameters
gravity_model = galileon
gravity_submodel = quintic
# Names:            xi,     c3
parameters_smg =  2.43, -0.132

# Other parameters:
hubble_evolution = yes
background_evolver = 0

# Standard Class parameters (best fit parameters from Barreira+ (1406.0485))
H0 = 76.19995
omega_cdm = 0.1231424
omega_b = 0.02201943
tau_reio = 0.06240824
A_s = 2.092228e-09
n_s = 0.9535994

# Output:
output = tCl, mPk 

root = output/galileon_5
overwrite_root = yes

output_background_smg = 10
write parameters = yeap
write background = yeah
write thermodynamics = yeahh

input_verbose = 1
background_verbose = 1
thermodynamics_verbose = 1
perturbations_verbose = 1
transfer_verbose = 1
primordial_verbose = 1
harmonic_verbose = 1
fourier_verbose = 1
lensing_verbose = 1
distortions_verbose = 1
output_verbose = 1
