# Example file for cubic covariant Galileon dark energy.
# See: Renk+17 (1707.02263) and Barreira+14 (1406.0485) for details

# Cubic Galileon theory: G_2 -> -X, G_3 -> c_3 X/(H_0^2M_p), G_4 -> M_p^2/2
# Notes:
# - all model parameters are fixed by Omega_smg and the tracker condition

# Switch on _smg fluid
Omega_Lambda = 0.
Omega_fld = 0.
Omega_smg = -1.

# For debugging purpouses one can specify a Omega_smg_debug
# AND unspecify Omega_smg,fld,Lambda so no shooting is done
# Omega_smg_debug = -1.

# Gravity model and parameters
gravity_model = galileon
gravity_submodel = cubic
# parameters_smg -> no extra parameters in cubic model

# Standard Class parameters (best fit parameters from Renk+17 (1707.02263))
H0 = 72.1429
omega_cdm = 0.119460
omega_b = 0.0219535
A_s = 2.09509e-09
n_s = 0960386
tau_reio = 0.0572286
#three degenerate massive neutrinos
N_ur = 0.00641 
N_ncdm = 1
deg_ncdm = 3
m_ncdm = 0.0181524

# Output:
output = tCl, mPk 

root = output/galileon_3nu
overwrite_root = yes

output_background_smg = 10
write parameters = yeap
write background = yeah
write thermodynamics = yeahh

input_verbose = 1
background_verbose = 1
thermodynamics_verbose = 1
perturbations_verbose = 1
transfer_verbose = 1
primordial_verbose = 1
harmonic_verbose = 1
fourier_verbose = 1
lensing_verbose = 1
distortions_verbose = 1
output_verbose = 1
