# Example file for nKGB model (Kinteic Gravity Braiding) dark energy.
# See: Kimura+ 11 (1110.3598), Deffayet+ 10 (1008.0048)

# nKGB model: G_2 -> -X, G_3 ->g^(n-1/2) Lambda (X/Lambda^4)^n, G_4 -> M_p^2/2
# Parameters:
# - Lambda -> (H0 Mp)^(1/3)
# - Rshift0: "off-trackerness": fraction of smg energy density today
#   in contribution from shift charge (0 <= Rshift0 < 1).
#   Rshift0 = Sqrt(2X) J / (Sqrt(2X) J + X)

# Switch on _smg fluid
Omega_Lambda = 0.
Omega_fld = 0.
Omega_smg = -1.

# For debugging purpouses one can specify a Omega_smg_debug
# AND unspecify Omega_smg,fld,Lambda so no shooting is done
# Omega_smg_debug = -1.

# Gravity model and parameters
gravity_model = nkgb
# Names:               g,   n,   Rshift0
parameters_smg =  4.e-05,  2.,        0.

# Output:
output = tCl, mPk 

root = output/nkgb
overwrite_root = yes

output_background_smg = 10
write parameters = yeap
write background = yeah
write thermodynamics = yeahh

input_verbose = 1
background_verbose = 1
thermodynamics_verbose = 1
perturbations_verbose = 1
transfer_verbose = 1
primordial_verbose = 1
harmonic_verbose = 1
fourier_verbose = 1
lensing_verbose = 1
distortions_verbose = 1
output_verbose = 1
